#include "util/geUtil.h"

namespace GE
{
  DEFINE_SERIAL_CLASS (GenericArrayList, CLSID_GENARRAYLIST);
  DEFINE_SERIAL_CLASS (GenericObjArrayList, CLSID_GENOBJARRAYLIST);
  DEFINE_SERIAL_CLASS (GenericPtrArrayList, CLSID_GENPTRARRAYLIST);
}
